config/routes.rb
Tweeter::Application.routes.draw do

  get "users/show"
  get "users/index"
  get "comments/recent"

  resources :comments

  resources :tweets

  root "welcome#index"

  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :configure_permitted_parameters, :only => [:create]

 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  include TweetsHelper
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end
  def recent

  end

  # GET /comments/new
  def new
    @comment = Comment.new

    @tweet_id = params["tweet_id"]
    @tweet = Tweet.find(@tweet_id)
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    @comment.user_id = current_user.id

    # update the number of comments for this tweet
    set_num_comments (params[:tweet_id])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:tweet_id, :user_id, :comment_text)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :photo_url, :email, :password) }
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    # get all the comments for this tweet
    @comments = @tweet.comments
    @num_comments = @comments.count
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
        
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :tweet, :num_comments)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
  
  def show
  	
  end

  def index
  	@users = User.all

  	@all_tweets = Tweet.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def set_num_comments(tweet_id)
		puts "hi guys"
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<!--
<form accept-charset="UTF-8" action="/comments" class="new_comment" id="new_comment" method="post">
-->
<!--

  <form accept-charset="UTF-8" action="/comments" class="new_comment" data-remote="true" id="new_comment" method="post">

  -->
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="response_message"></div>
  Add a comment to this tweet:
  <blockquote>
    <%=@tweet.tweet%>
  </blockquote>
  <div class="field">
    <%= f.label :comment_text %><br>
    <%= f.text_area :comment_text %>
  </div>
  <div class="actions">
    <%= f.hidden_field :tweet_id, :value=>@tweet_id%>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#response_message').append('<h1>Thanks for your comment <%=current_user.email%>');

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>User</th>
      <th>Comment text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.tweet_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.comment_text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/recent.html.erb
<h1>Listing recent comments</h1>

<div id="comments"><b>Haven't loaded comments yet! <a href="javascript:loadComments();">Click to load!</a></b></div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @comment.tweet_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Comment text:</strong>
  <%= @comment.comment_text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/update.js.erb
$('#save_message').append('You just tweeted THIS!! <h2><font color="red"><%= @tweet.tweet %></font></h2><br>');

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% if !user_signed_in? %>
      <%= link_to "Sign up", new_registration_path(:user), class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="nav pull-right">
      <% if !user_signed_in?  %>
        <% if controller.controller_name != "registrations" %>
        <%= form_for(:user, :url => session_path(:user), :html => {:class=>"navbar-form form-inline pull-right"}) do |f| %>
          <%= f.text_field :email, :class =>"form-control" %>
          <%= f.password_field :password, :class =>"form-control"  %>
          <%= f.submit 'Sign in', :class => "btn btn-primary" %>
          <% end %>
        <% end %>
       

      <% else %>
      <%= link_to "Sign out",destroy_user_session_path, method: :delete, class: "navbar-brand" %>
      <%= image_tag(current_user.photo_url) %>
     
      <% end %>
    </div>  
  
  
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tweeter" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tweeter" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="save_message"></div>

  <div class="field">
    <%= f.label :tweet %><br>
    <%= f.text_area :tweet, :cols => "70", :rows => "4", :placeholder => "I wanna see yo tweeeeetz...." %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/create.js.erb
$('#save_message').append('You just tweeted THIS!! <h2><font color="red"><%= @tweet.tweet %></font></h2><br>');

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tweet</th>
      <th>Num comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user_id %></td>
        <td><%= tweet.tweet %></td>
        <td><%= tweet.num_comments %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @tweet.tweet %></h2>
  <small>by: <%= @tweet.user.email %></small>
</p>

<%if @num_comments != 0%>
<!-- come in and clean this up! -->
<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>User</th>
      <th>Comment text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.tweet_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.comment_text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
	no comments. bummer.
	<%= link_to "Add a comment", new_comment_path(:tweet_id=>@tweet.id) %>
<%end%>

app/views/users/index.html.erb
<h1>Showing all users</h1>

<% @users.each do |user|



end %>

app/views/users/show.html.erb
<h1>Your Profile</h1>

Hi there <%=current_user.email%>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

<a href="javascript:convertSeconds(1393891200);">convert
	seconds</a>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Let's Make Tweeeeeeetz</h1>
<p>Find me in app/views/welcome/index.html.erb</p>


<%if user_signed_in? %>
You're logged in! What are you waiting for? <%=link_to "Add a new tweet now", new_tweet_path %>
<%end%>